---
#
# Ansible managed
#
repository:
  description: Grafana - platform for analytics and monitoring
  homepage: https://buluma.github.io/
  topics: grafana, dashboard, alerts, alerting, presentation, monitoring, metrics, ansible, molecule, tox, playbook, hacktoberfest
