---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "grafana-${image:-docker-centos7-ansible}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-centos7-ansible}:${tag:-latest}"
    exposed_ports:
      - 3000/tcp
    published_ports:
      - 0.0.0.0:3000:3000/tcp
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: yes
    tty: true
    environment:
      container: docker
provisioner:
  name: ansible
